### ISSUE TITLE
Settings option: Option to change background streams update interval (badge)

### ISSUE THREAD

**Issue by yungsamd17** [yungsamd17/Twitch-Live#14]
- [x] Load arbitrary update values from storage
- [x] Verify update period with different values
- [x] Verify / implement dynamic alarm period change
- [x] Settings UI for configuring period
  - [x] Design tweaks

**Comment by xezrunner** [comment]
UI:
We should probably style that dropdown as well as the input box to match the rest of the design.

<img width="400" alt="image" src="https://github.com/yungsamd17/Twitch-Live/assets/8061077/941497e8-60d8-42ea-8cba-4bda55e50b5f">
<img width="400" alt="image" src="https://github.com/yungsamd17/Twitch-Live/assets/8061077/c08ad7de-5a28-4ff8-900b-3fff10838df7">

**Comment by yungsamd17** [comment]
Nice looks good, but I think 1 hour should be enough as the last interval option. Also "60 minutes" instead "1 hour"

**Comment by xezrunner** [comment]
Tried making the dropdown look like the rest of the controls.
The badge color input field was not using its style, but it's probably WIP.

<img width="380" alt="image" src="https://github.com/yungsamd17/Twitch-Live/assets/8061077/d0d7bdb7-4070-4daf-8bd5-52b6f80f579c">
<img width="242" alt="image" src="https://github.com/yungsamd17/Twitch-Live/assets/8061077/3895ffc6-e7a8-4a36-8573-f787ef4f1506">

**Comment by xezrunner** [comment]
Pull request: https://github.com/yungsamd17/Twitch-Live/pull/16

Should test with the longer durations, although I'm fairly certain the 1, 2 and 5 minute options work.

**Comment by yungsamd17** [comment]
All update period values work
